version: "3.4"

services:
  webapp1:
    build:
      context: .
    image: docker-compose-nodejs-examples
    ports:
      - 8181:8080
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example