version: "3.4"

services:
  webapp1:
    build:
      context: .
    image: docker-compose-nodejs-examples
    cap_add: 
      - NET_ADMIN
      - SYS_ADMIN
    ports:
      - 8181:8080
    restart: always
