version: "3.4"

services:
  webapp1:
    build:
      context: .
      cache_from:
        - alpine:latest
    image: docker-compose-nodejs-examples-cache-from
    ports:
      - 8181:8080
    restart: always
